Paso 7 CI
andresarad1/cypress-training pull request #6
Opened 2023-10-04 20:18 UTC by andresarad1

2023-10-04 21:41 UTC, andresarad1 commented
![image](https://github.com/andresarad1/cypress-training/assets/134459852/a1e10391-75d0-4ef9-ba18-024391c49914)


Despues de unas correcciones, darme cuenta que algunos archivos quedaron duplicados, y revisar bien el archivo main.yml los test pasaron :D

2023-10-05 19:48 UTC, DanielCalleCO requested changes
Una pregunta, Tienes creado el archivo .gitignore?

2023-10-05 20:05 UTC, andresarad1 commented
> Una pregunta, Tienes creado el archivo .gitignore?

Si, si tengo el archivo

2023-10-05 20:19 UTC, DanielCalleCO approved these changes
Perdón, ya lo vi

2023-10-05 20:43 UTC, merged